import { MetricDefinition } from '@/types/programs';

export const PROGRAM_METRICS: MetricDefinition[] = [
  {
    key: 'body_weight',
    label: 'Body Weight',
    unit: 'kg',
    description: 'Total body weight measured under consistent conditions',
    goalTypes: ['fat_loss', 'muscle_gain', 'general_health'],
    direction: 'decrease',
    recommendedRange: { },
  },
  {
    key: 'body_weight_lb',
    label: 'Body Weight',
    unit: 'lb',
    description: 'Imperial unit alternative for body weight',
    goalTypes: ['fat_loss', 'muscle_gain', 'general_health'],
    direction: 'decrease',
  },
  {
    key: 'muscle_mass',
    label: 'Muscle Mass',
    unit: 'kg',
    description: 'Estimated lean muscle mass',
    goalTypes: ['muscle_gain', 'strength'],
    direction: 'increase',
  },
  {
    key: 'body_fat_pct',
    label: 'Body Fat %',
    unit: '%',
    description: 'Estimated body fat percentage',
    goalTypes: ['fat_loss', 'general_health'],
    direction: 'decrease',
    recommendedRange: { min: 8, max: 25 },
  },
  {
    key: 'ftp',
    label: 'Cycling FTP',
    unit: 'W',
    description: 'Functional Threshold Power',
    goalTypes: ['endurance'],
    direction: 'increase',
  },
  {
    key: '5k_time',
    label: '5K Time',
    unit: 'min',
    description: 'Time to complete 5 kilometers',
    goalTypes: ['endurance'],
    direction: 'decrease',
  },
  {
    key: 'marathon_time',
    label: 'Marathon Time',
    unit: 'min',
    description: 'Time to complete marathon distance',
    goalTypes: ['endurance'],
    direction: 'decrease',
  },
  {
    key: 'one_rep_max_total',
    label: 'Total 1RM (S/B/D)',
    unit: 'kg',
    description: 'Sum of single-rep maxes for squat/bench/deadlift',
    goalTypes: ['strength'],
    direction: 'increase',
  },
  {
    key: 'weekly_training_adherence',
    label: 'Plan Adherence',
    unit: '%',
    description: 'Percent of planned sessions completed',
    goalTypes: ['muscle_gain', 'fat_loss', 'endurance', 'strength', 'general_health'],
    direction: 'increase',
  },
];
